name: Add Label to Issues

on:
  issues:
    types:
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check Issue Name
        id: check-issue
        run: |
          issue_title="${{ github.event.issue.title }}"
          if [[ $issue_title == "varyadaser"* ]]; then
            echo "MATCH_FOUND=true" >> $GITHUB_ENV
          else
            echo "MATCH_FOUND=false" >> $GITHUB_ENV
          fi
          
      - name: Add Label
        if: env.MATCH_FOUND == 'true'
        run: |
          echo "daser"
