name: Add Label to Issues

on:
  issues:
    types:
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check Issue Name
        id: check-issue
        run: |
          issue_title="${{ github.event.issue.title }}"
          if [[ $issue_title == "varyadaser"* ]]; then
            echo "MATCH_FOUND=true" >> $GITHUB_ENV
          else
            echo "MATCH_FOUND=false" >> $GITHUB_ENV
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Add Label
        if: env.MATCH_FOUND == 'true'
        run: |
          npm install -g @actions/github-script
          label='daser'
          issueNumber=${{ github.event.issue.number }}
          npx github-label -t ${{ secrets.GITHUB_TOKEN }} -o ${{ github.repository_owner }} -r ${{ github.repository }} -i $issueNumber -l $label
